GroceryListBuilder/Models/APICall.cs
using GroceryListBuilder.Models;
using Newtonsoft.Json.Linq;

namespace APICall
{
    class APICall
    {
        public static Meal GetMeal(string recipe)
        {
            var client = new HttpClient();
           

            var foodURL = $"https://www.themealdb.com/api/json/v1/1/search.php?s={recipe}";
            var response = client.GetStringAsync(foodURL).Result;

            JObject formattedResponse = JObject.Parse(response);
            var instance = new Meal();
            instance.StrMeal = formattedResponse["meals"][0]["strMeal"].ToString();

            instance.StrInstructions = formattedResponse["meals"][0]["strInstructions"].ToString();

            instance.StrPhoto = formattedResponse["meals"][0]["strMealThumb"].ToString();

            instance.StrIngredient1 = formattedResponse["meals"][0]["strIngredient1"].ToString();
            instance.StrIngredient2 = formattedResponse["meals"][0]["strIngredient2"].ToString();
            instance.StrIngredient3 = formattedResponse["meals"][0]["strIngredient3"].ToString();
            instance.StrIngredient4 = formattedResponse["meals"][0]["strIngredient4"].ToString();
            instance.StrIngredient5 = formattedResponse["meals"][0]["strIngredient5"].ToString();
            instance.StrIngredient6 = formattedResponse["meals"][0]["strIngredient6"].ToString();
            instance.StrIngredient7 = formattedResponse["meals"][0]["strIngredient7"].ToString();
            instance.StrIngredient8 = formattedResponse["meals"][0]["strIngredient8"].ToString();
            instance.StrIngredient9 = formattedResponse["meals"][0]["strIngredient9"].ToString();
            instance.StrIngredient10 = formattedResponse["meals"][0]["strIngredient10"].ToString();

            return instance;
        }
    }
}

GroceryListBuilder/Models/ErrorViewModel.cs
namespace GroceryListBuilder.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GroceryListBuilder/Models/Meal.cs
namespace GroceryListBuilder.Models
{
    public class Meal
    {
        public string StrMeal { get; set; }
        public string StrInstructions { get; set; }
        public string StrPhoto { get; set; }

        public string Recipe { get; set; }
        public string StrIngredient1 { get; set; }
        public string StrIngredient2 { get; set; }
        public string StrIngredient3 { get; set; }
        public string StrIngredient4 { get; set; }
        public string StrIngredient5 { get; set; }
        public string StrIngredient6 { get; set; }
        public string StrIngredient7 { get; set; }
        public string StrIngredient8 { get; set; }
        public string StrIngredient9 { get; set; }
        public string StrIngredient10 { get; set; }

        public List<string>? FoodOptions { get; set; } = new List<string>() { "taco", "pizza", "enchilada", "spaghetti"}; 
    }
}

GroceryListBuilder/Controllers/HomeController.cs
using System.Diagnostics;
using GroceryListBuilder.Models;
using Microsoft.AspNetCore.Mvc;


namespace GroceryListBuilder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

GroceryListBuilder/Controllers/MealController.cs
using GroceryListBuilder.Models;
using Microsoft.AspNetCore.Mvc;

namespace GroceryListBuilder.Controllers
{
    public class MealController : Controller
    {
        public IActionResult RecipeIndex(Meal mealName)
        {
            var api = APICall.APICall.GetMeal(mealName.StrMeal);
            return View(api);
        }
    }
}

GroceryListBuilder/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using GroceryListBuilder.Models
@model Meal

<div class="text-center">
    <h1 class="display-4">Welcome To The Grocery List Builder.</h1>
    <p>Lets make you a shopping list</a>.</p>

    @using (Html.BeginForm("RecipeIndex", "Meal", "Post"))
    {
        <div class="form-group">

            <label class="title" for="">Select a meal</label>
            <br />
            <select class="form-control  form-select" name="StrMeal" value="">
                
                
                    <option value="Taco">taco</option>
                    <option value="Pizza">pizza</option>
                    <option value="Enchilada">enchilada</option>
                    <option value="Burger">burger</option>
                    <option value="Crumble">crumble</option>
                    <option value="Pot Roast">pot roast</option>
                    <option value="Pancakes">pancakes</option>
                    <option value="Cake">cake</option>
                    <option value="Stroganoff">stroganoff</option>
                    <option value="Tart">tart</option>
                    <option value="Potatoes">potatoes</option>
                    <option value="Big Mac">big mac</option>
                    <option value="Banh Mi">banh mi</option>
                    <option value="Brownies">brownies</option>
                    <option value="Cookie">cookie</option>
                
                
                    
                
            </select>
        </div>
        <br /> <br />

        <br />

        <br />
        <input type="submit" value="Submit Choice" class="btn btn-primary" />



    }
</div>

GroceryListBuilder/Views/Meal/RecipeIndex.cshtml
@model Meal

<h1>@Model.StrMeal</h1>

<p>@Model.StrInstructions</p>

<img src=@Model.StrPhoto />

<ol>

    @if (Model != null && Model.StrIngredient1.Count() != 0)
    {
        <li>@Model.StrIngredient1</li>
    }

    @if (Model != null && Model.StrIngredient2.Count() != 0)
    {
        <li>@Model.StrIngredient2</li>
    }

    @if (Model != null && Model.StrIngredient3.Count() != 0)
    {
        <li>@Model.StrIngredient3</li>
    }

    @if (Model != null && Model.StrIngredient4.Count() != 0)
    {
        <li>@Model.StrIngredient4</li>
    }

    @if (Model != null && Model.StrIngredient5.Count() != 0)
    {
        <li>@Model.StrIngredient5</li>
    }

    @if (Model != null && Model.StrIngredient6.Count() != 0)
    {
        <li>@Model.StrIngredient6</li>
    }

    @if (Model != null && Model.StrIngredient7.Count() != 0)
    {
        <li>@Model.StrIngredient7</li>
    }

    @if (Model != null && Model.StrIngredient8.Count() != 0)
    {
        <li>@Model.StrIngredient8</li>
    }

    @if (Model != null && Model.StrIngredient9.Count() != 0)
    {
        <li>@Model.StrIngredient9</li>
    }

    @if (Model != null && Model.StrIngredient10.Count() != 0)
    {
        <li>@Model.StrIngredient10</li>
    }



</ol>

GroceryListBuilder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GroceryListBuilder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GroceryListBuilder.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="index.css" />   @*css attatchment*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GroceryListBuilder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GroceryListBuilder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>